#from src.database import get_session, PurchaseOrder
import os
#from unittest import result
from dotenv import load_dotenv
import sqlite3
# Create a shared SQLite database for the checkpointer
CHATCHECKPOINT_DB = "langgraph_chatcheckpoints.db"
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from typing import Sequence, List, final
from langchain.tools import tool
from langchain_core.tools import StructuredTool
from langchain_groq import ChatGroq
from typing import TypedDict, Optional, Dict, Any, Annotated
from langgraph.graph.message import add_messages
from langgraph.graph import StateGraph, START, END
from pydantic import BaseModel, Field, config
from typing import Optional, List
from typing import Dict, Any
from langgraph.checkpoint.memory import MemorySaver
from langchain_core.messages import BaseMessage
from operator import add
from langgraph.checkpoint.sqlite import SqliteSaver
from langgraph.graph.message import add_messages


memory = MemorySaver()
load_dotenv()

#LANGSMITH_TRACING="true"

LANGSMITH_ENDPOINT=os.getenv("LANGSMITH_ENDPOINT")
LANGSMITH_API_KEY=os.getenv("LANGSMITH_API_KEY")
LANGSMITH_PROJECT=os.getenv("LANGSMITH_PROJECT")
LANGCHAIN_TRACING_V2=os.getenv("LANGCHAIN_TRACING_V2")


llm = ChatGroq(model="llama-3.3-70b-versatile",
                   temperature=0.3,
                   max_tokens=300,
                   groq_api_key=os.getenv("GROQ_API_KEY"))


"""
LangGraph State definition.
This is the shared memory that flows between all agents in the workflow.
"""
class TextToQueryState(TypedDict):
    """
    The state that flows through the Text to Query agent graph.
    
    Text to Agent reads from this state, performs its task, and updates it.
    """
    # Initial input
    #user_msg: str  # The natural language question (e.g., "Is Store 4 low on(bellow reorder value) on Organic Milk")
    #user_msg: Annotated[list[str],add]
    #messages: Annotated[list, add_messages]
    messages: Annotated[list, add_messages]
    schemas_info: Optional[Dict[str, Any]] # Schema information for the relevant database tables
    sql_query_from_ai: Optional[str] #sql query generated by AI
    final_ai_reply:Optional[str] # final reply generated by AI
    table_names: Optional[Dict[str, Any]] # db table names
    raw_rows: Optional[Dict[str, Any]] # query result rows
    raw_cols: Optional[Dict[str, Any]] # query result columns
    
    


def get_connection():
    return sqlite3.connect(os.getenv("sqllightlink"))


def user_input_from_ui(state:TextToQueryState):
    print("---Node 1---")
    print("State keys:", list(state.keys()))
    print("Messages:", state['messages'])
    return {"user_msg": state['messages'][-1].content }  # Get the last user message from the messages list


def table_names(state:TextToQueryState):
    
    conn=get_connection()
    # Connect to the database
    cursor = conn.cursor()

    # Query for table names
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    tables = cursor.fetchall()

    # Extract names from the list of tuples
    table_names = [table[0] for table in tables]
    return {"table_names": table_names}

     
def get_schema(state:TextToQueryState):
    table_names = state['table_names']
    
    """Return a compact, human‑readable schema description."""
    conn = get_connection()
    cursor = conn.cursor()
    """Get the schema for specified tables."""
    
    lines: List[str] = []
    
    #conn = get_connection()
    # ------------------------------------------------------------------
    # 2️⃣ Iterate over the supplied table names.
    # ------------------------------------------------------------------
    for raw_name in table_names:
        table = raw_name.strip()
        if not table:                 # skip empty entries like "" or "   "
            continue

        # --------------------------------------------------------------
        # 3️⃣ Quote the identifier safely.
        # --------------------------------------------------------------
        #   * Escape any double‑quote that may already be present.
        #   * Surround the whole identifier with double‑quotes.
        escaped = table.replace('"', '""')
        safe = f'"{escaped}"'          # <-- works because we escaped first

        # --------------------------------------------------------------
        # 4️⃣ Ask SQLite for the column info.
        # --------------------------------------------------------------
        cursor.execute(f"PRAGMA table_info({safe})")
        cols = cursor.fetchall()      # [(cid, name, type, notnull, dflt, pk), …]

        # --------------------------------------------------------------
        # 5️⃣ Build a readable line for this table.
        # --------------------------------------------------------------
        lines.append(f"Table: {table}, Columns: {cols}")
        #conn.close()
        # ------------------------------------------------------------------
        # 6️⃣ Return everything joined by newlines.
        # ------------------------------------------------------------------
    #return "\n".join(lines)
    return {"schemas_info":lines}


def create_sql(state:TextToQueryState):
    Schema_Info = state['schemas_info']

    user_msg = state["messages"][-1].content  # Get the last user message from the messages list

    system_prompt = f"""
                    SQLite expert. 
                    Given schema: {Schema_Info} Generate ONLY the SELECT query. No markdown, no explanation."""

    response = llm.invoke([SystemMessage(content=system_prompt)] + [HumanMessage(content=user_msg)])
    proposal = response.content

    #return {"final_answer": proposal}
    return {"sql_query_from_ai": proposal}

def exe_sql(state:TextToQueryState):
    final_ans = state['sql_query_from_ai']
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(final_ans)
    rows = cursor.fetchall()
    columns =[desc[0] for desc in cursor.description]
    dict_rows =[dict(zip(columns, r)) for r in rows]
    
    return{"raw_cols": columns, "raw_rows":dict_rows}


def final_ai_reply(state:"TextToQueryState"):
    data= state['raw_rows']
    schema_info=state['schemas_info']


    promptsss = f"""You are a senior supply chain AI assistant. You human supply chain manager to understand complex SQL response.

            CONTEXT:
                - User ask (business question:{state['messages'][-1].content})
                - That question was already converted to (SQL query: {state['sql_query_from_ai']})
            TASK:
                Write a concise, professional proposal (3-4 sentences) that:
                    1. States the result clearly using the business question and sql query response.
                    2. check if reorder is needed for the stock.
                    4. Sounds confident and data-driven.
            Be direct and factual.    
            """

    system_msg = f"""
    **Task**: You are an expert AI supply chain agent which help supply chain business leader to understand and manager merchandise.

    **SQL db Schema data**:
    {schema_info}
    """

    prompt_content = f"""
    **Task**: Analyze the following inventory status and recommend an immediate action.

    **Inventory Data**:
    {data}

    **Constraints**:
    - If current_stock < reorder_point, flag as "CRITICAL".
    - Calculate the deficit (reorder_point - current_stock).
    - Draft a short notification for the procurement team.
    """
    
    response2 = llm.invoke([SystemMessage(content=system_msg)] + [HumanMessage(content=prompt_content)])
    proposal2 = response2.content
    #return {"final_text": proposal2}
    return {"final_ai_reply": proposal2}


builder = StateGraph(TextToQueryState)

#Add nodes
builder.add_node("user_input", user_input_from_ui)
builder.add_node("dbtable", table_names)
builder.add_node("getschema", get_schema)
builder.add_node("createsql", create_sql)
builder.add_node("exesql", exe_sql)
builder.add_node("finalaireply", final_ai_reply)

#define the flow
builder.add_edge(START,"user_input")
builder.add_edge("user_input","dbtable")
builder.add_edge("dbtable","getschema")
builder.add_edge("getschema","createsql")
builder.add_edge("createsql","exesql")
builder.add_edge("exesql","finalaireply")
builder.add_edge("finalaireply",END)


conn = sqlite3.connect(CHATCHECKPOINT_DB, check_same_thread=False)
chatcheckpointer = SqliteSaver(conn)

#config = {"configurable": {"thread_id": "1"}}
app = builder.compile(checkpointer=chatcheckpointer)






# result = app.invoke({"user_msg":"is this stock below reorder level?"}, config= config)


# print(f"user input: {result['user_msg']}")
# print(f"table names: {result['table_names']}")
# print(f"schema info: {result['schemas_info']}")
# print(f"raw columns: {result['raw_cols']}")
# print(f"sql query: {result['sql_query_from_ai']}")
# print(f"final AI reply: {result['final_ai_reply']}")



# --------------------------------------------------------------
# 10️⃣ Helper to run the whole pipeline in one call
# --------------------------------------------------------------
def answer_question(question: str,config: dict) -> str:
#     """Convenient wrapper – returns the final markdown answer."""
    result = app.invoke({"messages": [HumanMessage(content=question)]}, config=config)
     #return result["final_text"]
     #return
     #return mm["final_ai_reply"] 
     #return {"reply": result.final_ai_reply}
    print("Full result:", result)  # ← See the entire dictionary
    print("Final reply:", result["final_ai_reply"])  # ← See just the answer
    return result["final_ai_reply"]
